version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tzdb
    ports:
      - "5432:5432"

  api:
    restart: unless-stopped
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file: "./api/.env"
    depends_on:
      - db

  client:
    restart: unless-stopped
    build:
      context: ./client
      target: dev
    volumes:
      - ./client:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - api
